version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/leaderboard', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Optional: PostgreSQL service if you want to run DB locally
  # Uncomment if you want Coolify to manage your database
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-auditech_user}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB:-rubberdev}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   postgres_data:
